name: Run Python Unit Tests
on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install Python 3
        uses: actions/setup-python@v4.2.0
        with:
          cache: 'pip' # caching pip dependencies
          check-latest: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
